/* Controle 360 · interface do Radar, usando somente dados carregados no dashboard. */
(function(){
'use strict';
const C=window.RadarCore,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const R=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v||0);
const pct=v=>C.n(v)===null?'—':Number(v).toLocaleString('pt-BR',{maximumFractionDigits:2})+'%';
const num=v=>C.n(v)===null?'—':Number(v).toLocaleString('pt-BR',{maximumFractionDigits:2});
const date=v=>Number.isFinite(Date.parse(v))?new Date(v.length===10?v+'T12:00:00':v).toLocaleString('pt-BR',v.length===10?{dateStyle:'short'}:{dateStyle:'short',timeStyle:'short'}):'data indisponível';
const safeURL=v=>{try{const u=new URL(v);return u.protocol==='https:'?u.href:''}catch{return ''}};
let conta='',prefs={},mercado=null,erro='',carregando=false,aba='destaques',ultimo=0;
const Q=[
 ['Qual o prazo principal para este dinheiro?',['Até 2 anos','De 2 a 5 anos','Mais de 5 anos']],
 ['Se a carteira caísse 20%, como você reagiria?',['Não toleraria essa perda','Reavaliaria antes de decidir','Aceitaria a oscilação com planejamento']],
 ['Quanto deste dinheiro pode ficar aplicado?',['Posso precisar a qualquer momento','Parte pode ficar por alguns anos','A maior parte pode ficar por mais de 5 anos']],
 ['Qual sua experiência com investimentos?',['Estou começando','Já conheço diferentes classes','Entendo riscos e já invisto em ativos voláteis']],
 ['Qual combinação faz mais sentido para você?',['Menor oscilação, mesmo com retorno menor','Equilíbrio entre estabilidade e crescimento','Aceitar perdas maiores buscando crescimento']]
];
function carregar(email){if(conta===email)return;conta=email;mercado=null;erro='';ultimo=0;aba='destaques';try{prefs=JSON.parse(localStorage.getItem('c360-radar-v1:'+email)||'{}')||{}}catch{prefs={}};if(typeof prefs!=='object'||Array.isArray(prefs))prefs={};}
function salvar(){try{localStorage.setItem('c360-radar-v1:'+conta,JSON.stringify(prefs));return true}catch{return false}}
function perfilHTML(p){return `<section class="panel radar-perfil"><div class="radar-section"><span class="radar-step">01</span><h2>Seu perfil</h2><span class="radar-pill">${p||'Ainda não definido'}</span></div><p class="sub">Perfil individual · salvo neste navegador para sua conta. Para planejar o dinheiro do casal, conversem sobre a tolerância de ambos.</p>
 <details ${p?'':'open'}><summary>${p?'Revisar questionário':'Responder 5 perguntas'}</summary><form id="radarPerfil" class="radar-questionario">${Q.map(([q,op],i)=>`<fieldset><legend>${i+1}. ${q}</legend>${op.map((o,j)=>`<label class="radar-radio"><input type="radio" name="rp${i}" value="${j}" required ${prefs.respostas?.[i]===j?'checked':''}><span>${o}</span></label>`).join('')}</fieldset>`).join('')}<button class="btn" type="submit">Salvar meu perfil</button><p class="nota" id="radarPerfilMsg" role="status"></p></form></details></section>`;}
function distribuicao(a,p,d){return `<section class="panel"><div class="radar-section"><span class="radar-step">03</span><h2>Carteira atual × cenário sugerido</h2></div><p class="sub">Reserva cadastrada + investimentos: <b class="ref">${R(a.total)}</b>. Caixa e metas comuns ficam fora desta comparação.</p>
 ${!p?'<p class="radar-empty">Responda ao questionário para visualizar um cenário educativo.</p>':`<p class="nota">${a.meses!==null&&a.meses<6?'Prioridade: formar a reserva. O cenário concentra os próximos esforços em liquidez até atingir a referência de 6 meses.':a.curtas.length?'Metas próximas aumentam a participação ilustrativa em liquidez e renda fixa.':'Cenário ilustrativo pelo perfil '+p+'. Os percentuais são parâmetros do sistema.'} Não é uma ordem para vender ou rebalancear a carteira.</p>`}
 <div class="radar-legend"><span>● Carteira atual</span><span class="ref">▱ Cenário educativo</span></div>${C.CLASSES.map(([id,nome,cor])=>{const atual=a.total>0?a.por[id]/a.total*100:0,alvo=a.sugerida?.[id];return `<div class="radar-allocation"><div><b>${nome}</b><span>${a.total>0?pct(atual):'Sem saldo'} ${alvo!==undefined?' / <b class="ref">'+pct(alvo)+'</b>':''}</span></div><div class="radar-track" aria-label="${nome}: atual ${pct(atual)}"><i style="width:${Math.min(100,atual)}%;background:${cor}"></i></div>${alvo!==undefined?`<div class="radar-track target" aria-label="Cenário ${pct(alvo)}"><i style="width:${alvo}%;background:${cor}"></i></div>`:''}</div>`}).join('')}
 <details><summary>Ajustar a classificação da carteira</summary><p class="nota">Confirme ETFs, fundos e aplicações de reserva. Marcar como reserva inclui o saldo na cobertura de emergência: use apenas dinheiro realmente disponível para imprevistos. O tipo cadastrado não revela sempre a exposição ou a liquidez. Para evitar duplicidade, dinheiro da reserva deve estar cadastrado em apenas uma das abas.</p>${d.invest.length?d.invest.map(x=>`<label class="radar-class"><span>${esc(x.produto||x.nome||x.tipo)}${x.produto&&x.nome?' · '+esc(x.nome):''}</span><select class="field" data-radar-class="${esc(x.id)}" aria-label="Classe de ${esc(x.nome||x.produto||x.tipo)}">${C.CLASSES.map(([id,n])=>`<option value="${id}" ${C.classe(x,prefs.classes)===id?'selected':''}>${n}</option>`).join('')}</select></label>`).join(''):'<p class="nota">Cadastre seus investimentos para comparar.</p>'}</details></section>`;}
function metodologia(){return `<details class="radar-method"><summary>Como o Radar calcula e avalia?</summary><p>Caixa livre = caixa atual − compromissos do mês (inclusive atrasados). Salários futuros não entram. O saldo para planejar desconta também verba pessoal restante e aportes planejados para metas. A sobra estimada preserva mais um mês de gastos médios no caixa, além da reserva já guardada.</p><p>A reserva usa a média de gastos do dashboard e a referência de 6 meses. Metas até 2 anos pedem menor oscilação; a partir de 5 anos permitem estudar maior risco. Dívidas a partir de 2% ao mês acionam uma prioridade de revisão. Estes limites são escolhas educativas do sistema e podem não representar a sua necessidade real.</p><p>Nas ações, a nota é a média simples de quatro critérios de 0 a 10: P/L, dividend yield, ROE e dívida/patrimônio. Cada faixa aparece em “Por que recebeu essa nota?”. Sem os quatro dados, não há nota nem ranking. Notas de 8 ou mais são atrativas pelos critérios, de 5 a 7,99 são neutras e abaixo de 5 são pouco atrativas. Não há comparação setorial, análise de governança ou previsão de retorno; especialmente bancos e empresas cíclicas exigem análise adicional.</p><p>CDB, LCI e LCA são ordenados pela rentabilidade líquida percentual estimada até o vencimento entre ofertas verificadas cadastradas na fonte. Não é um ranking de todo o mercado. O CDI é uma premissa constante; as datas, o valor mínimo e a liquidez limitam a comparação. Ofertas vencidas ou com verificação de mais de 24 horas não participam. Não há nota inventada para renda fixa.</p><p>Dados de mercado com mais de 96 horas ficam fora dos destaques e aparecem como desatualizados. Cotações podem ter atraso. “Atrativa” mede apenas os critérios, não adequação ao seu perfil ou autorização para comprar.</p></details>`;}
function acaoCard(x){const s=C.notaAcao(x),stale=!C.recente(x.asOf),cor=s.nota===null?'info':s.nota>=8?'ok':s.nota>=5?'atencao':'alerta';return `<article class="radar-market-card"><div class="radar-section"><h3>${esc(x.ticker)}</h3><span class="radar-pill">${s.nota===null?'Sem nota':num(s.nota)+'/10'}</span></div><p>${esc(x.name||'')}</p><b class="radar-price">${C.n(x.price)===null?'—':R(x.price)}</b><span class="radar-status ${cor}">${stale?'Dados desatualizados · fora do ranking':s.status}</span><div class="radar-metrics"><span>P/L <b>${num(x.pl)}</b></span><span>DY <b>${pct(x.dy)}</b></span><span>ROE <b>${pct(x.roe)}</b></span><span>Dívida / PL <b>${num(x.debtEquity)}x</b></span><span>Variação no pregão <b>${pct(x.change)}</b></span><span>Risco <b>alto · renda variável</b></span></div><details><summary>Por que recebeu essa nota?</summary>${s.criterios.map(c=>`<p><b>${c.nome}: ${c.nota===null?'não informado':c.nota+'/10'}</b><br>${c.regra}</p>`).join('')}<p>Peso de cada critério: 25%. Desempenho do pregão é informativo e não entra na nota. Dados incompletos não recebem nota.</p></details><small class="mut">${esc(x.source)} · cotação ${date(x.asOf)}${x.fundamentalDate?' · balanço '+esc(x.fundamentalDate):''}</small></article>`;}
function ofertaValida(x){return ['CDB','LCI','LCA'].includes(x.type)&&x.verified===true&&C.recente(x.checkedAt,24)&&Date.parse(x.maturity+'T23:59:59')>Date.now()&&!!safeURL(x.url)&&C.n(x.rate)>0&&['cdi','prefixado'].includes(x.indexer)&&['diaria','vencimento'].includes(x.liquidity)&&typeof x.issuer==='string'&&x.issuer.trim();}
function ofertaSim(x,valor){const dias=Math.max(1,Math.ceil((Date.parse(x.maturity+'T12:00:00')-Date.now())/864e5));return C.simular({capital:valor,dias,taxa:Number(x.rate),tipo:x.indexer,cdi:mercado?.cdi?.annual,isento:x.taxExempt===true});}
function ofertaCard(x,a){const capital=Math.max(1000,Number(x.min)||0),r=ofertaSim(x,capital);return `<article class="radar-market-card"><h3>${esc(x.type)} · ${esc(x.issuer)}</h3><b class="radar-price">${num(x.rate)}${x.indexer==='cdi'?'% do CDI':'% a.a.'}</b><p>${x.liquidity==='diaria'?'Liquidez diária conforme a oferta':'Resgate somente no vencimento'} · vence ${date(x.maturity)}</p><div class="radar-metrics"><span>Mínimo <b>${R(x.min||0)}</b></span><span>FGC <b>${x.fgc===true?'Cobertura informada':x.fgc===false?'Sem cobertura informada':'Não confirmado'}</b></span><span>Base simulada <b>${R(capital)}</b></span><span>Lucro líquido estimado <b>${r?R(r.liquido):'CDI indisponível'}</b></span><span>Retorno no prazo <b>${r?pct(r.retorno):'—'}</b></span><span>IR estimado <b>${r?pct(r.irAliq*100):'—'}</b></span></div><p class="nota">${x.liquidity==='vencimento'?'Atenção: o dinheiro fica preso até o vencimento.':'Confira carência, horário e prazo de crédito do resgate.'} ${a.capacidade<Number(x.min||0)?'A sobra estimada está abaixo do aporte mínimo.':''}</p><details><summary>Por que aparece no Radar?</summary><p>Oferta verificada na fonte nas últimas 24 horas. A ordenação compara retorno líquido percentual até cada vencimento, que pode ter prazo diferente. Simulação com CDI constante, sem taxas, com IR/IOF quando aplicável. Disponibilidade e cobertura precisam ser confirmadas com o emissor.</p></details><a class="lnk" href="${esc(safeURL(x.url))}" target="_blank" rel="noopener noreferrer">Conferir na fonte →</a><small class="mut">${esc(x.source)} · verificada ${date(x.checkedAt)}</small></article>`;}
function tesouroCard(x){const stale=!C.recente(x.asOf),nome=(x.name||'').toLowerCase(),selic=nome.includes('selic'),ipca=nome.includes('ipca'),rotulo=selic?'Selic + ':ipca?'IPCA + ':'';return `<article class="radar-market-card"><h3>${esc(x.name)}</h3><b class="radar-price">${C.n(x.rate)===null?'Taxa indisponível':rotulo+num(x.rate)+'% a.a.'}</b><p>Vencimento: ${date(x.maturity)}</p><p>${selic?'Para estudar objetivos de menor oscilação e reserva, observando prazo de crédito do resgate.':ipca?'Para estudar objetivos de longo prazo e proteção contra inflação, com vencimento compatível.':'Para estudar objetivos com prazo definido e taxa nominal contratada, mantendo até o vencimento.'}</p><p class="nota">${selic?'A taxa exibida é o adicional sobre a Selic, não o retorno total.':'Venda antecipada pode resultar em perda por marcação a mercado.'} ${stale?'Data-base desatualizada.':''}</p><small class="mut">${esc(x.source)} · data-base ${date(x.asOf)}</small></article>`;}
function mercadoHTML(a,p){const stocks=Array.isArray(mercado?.stocks)?mercado.stocks:[],treasury=Array.isArray(mercado?.treasury)?mercado.treasury:[],offers=(Array.isArray(mercado?.offers)?mercado.offers:[]).filter(ofertaValida);const ranked=stocks.filter(x=>C.recente(x.asOf)&&C.notaAcao(x).nota!==null).sort((x,y)=>C.notaAcao(y).nota-C.notaAcao(x).nota);
 const ordered=offers.sort((x,y)=>(ofertaSim(y,1000)?.retorno??-1)-(ofertaSim(x,1000)?.retorno??-1));
 let cards='',empty='';
 if(aba==='acoes'){cards=stocks.map(acaoCard).join('');empty='Sem cotações carregadas. Atualize o mercado após ativar a conexão.';}
 else if(aba==='cdb'||aba==='fixa'){cards=ordered.filter(x=>aba==='cdb'?x.type==='CDB':['LCI','LCA'].includes(x.type)).map(x=>ofertaCard(x,a)).join('');empty='Nenhuma oferta verificada disponível nesta fonte. Ofertas privadas de corretoras podem não aparecer.';}
 else if(aba==='tesouro'){cards=treasury.map(tesouroCard).join('');empty='Sem taxas carregadas. Confira os títulos e taxas no site oficial do Tesouro Direto.';}
 else {cards=ranked.slice(0,5).map(acaoCard).join('');empty='O Top 5 aparece quando houver ações com dados suficientes e atualizados. É uma seleção do universo consultado, não de toda a Bolsa.';}
 return `<div class="radar-market-head"><div><h3>Radar do mercado</h3><p class="sub">${mercado?'Consulta em '+date(mercado.fetchedAt):'Conexão de mercado ainda não ativada'}</p></div><button type="button" class="btn ghost" data-radar="atualizar" ${carregando?'disabled':''}>${carregando?'Consultando…':'Atualizar mercado'}</button></div><p class="nota" role="status">${esc(erro)}${mercado?.warnings?.length?' '+mercado.warnings.map(esc).join(' · '):''}</p>
 ${p==='Conservador'||a.bloqueado||a.meses===null||a.meses<6?'<p class="radar-hint">Destaques são informações de mercado. Seu planejamento prioriza liquidez e proteção dos compromissos; uma nota alta não torna uma ação adequada para este dinheiro.</p>':''}
 <div class="radar-tabs" role="tablist" aria-label="Classes de investimento">${[['destaques','⭐ Top 5 de ações'],['acoes','📈 Ações'],['cdb','🏦 CDBs'],['tesouro','🇧🇷 Tesouro'],['fixa','💰 LCI / LCA']].map(([id,n])=>`<button type="button" role="tab" aria-selected="${aba===id}" data-radar-tab="${id}">${n}</button>`).join('')}</div><div class="radar-market-grid" role="tabpanel">${cards||'<p class="radar-empty">'+empty+'</p>'}</div>`;
}
function simulador(){return `<details class="radar-simulator"><summary>Simular renda fixa após impostos</summary><p class="nota">Cenário hipotético, independente das ofertas. ${mercado?.cdi?'CDI de referência: '+pct(mercado.cdi.annual)+' a.a. · '+date(mercado.cdi.asOf):'Informe a premissa anual de CDI.'}</p><form id="radarSim" class="radar-sim-form"><label>Valor (R$)<input class="field" name="capital" inputmode="decimal" value="1000" required></label><label>Prazo em dias corridos<input class="field" name="dias" inputmode="numeric" value="365" required></label><label>Remuneração<select class="field" name="tipo"><option value="cdi">% do CDI</option><option value="prefixado">Prefixado (% ao ano)</option></select></label><label>Taxa contratada<input class="field" name="taxa" inputmode="decimal" value="100" required></label><label>CDI hipotético (% a.a.)<input class="field" name="cdi" inputmode="decimal" value="${C.n(mercado?.cdi?.annual)??''}" placeholder="Ex.: 10" ></label><label class="radar-radio"><input type="checkbox" name="isento"><span>Produto isento de IR e IOF para este investidor (confirmar na fonte)</span></label><button type="submit" class="btn">Calcular estimativa</button><div id="radarSimResultado" class="radar-sim-result" role="status"></div></form><p class="nota">IR regressivo sobre o ganho após IOF. IOF até 29 dias nos produtos tributáveis. Estimativa sem taxas, sem inflação e sem risco de mercado; aproximação de dias úteis (252/ano). Tributação pode mudar: confirme a regra aplicável ao produto e ao investidor.</p></details>`;}
function render(d){carregar(d.email);const p=C.perfil(prefs.respostas),a=C.analisar(d,p,prefs.classes||{});return `<div class="radar"><div class="view-head"><div><h1>🔎 Radar de Investimentos</h1><p>Seu dinheiro, seus objetivos e caminhos para o próximo passo.</p></div><span class="radar-pill">Planejamento educativo</span></div>
 <div class="tiles radar-tiles">${[['Em caixa',a.caixa,'saldo atual'],['Compromissos',a.compromissos,'registrados para o mês + atrasados'],['Caixa livre',a.livre,'caixa − compromissos'],['Sobra estimada',a.sobra,'após verba, metas e colchão de caixa']].map(([nome,v,sub])=>`<div class="tile"><div class="k">${nome}</div><div class="v ${v<0?'neg':'ref'}">${R(v)}</div><div class="d">${sub}</div></div>`).join('')}</div>
 <details class="panel radar-cash"><summary>Entenda a sobra estimada</summary><div class="radar-cash-lines">${[['Caixa livre',a.livre],['Verba pessoal restante',-a.verba],['Aportes planejados para metas',-a.metasMes],['Saldo para planejar',a.planejavel],['Colchão de caixa: 1 mês de gastos médios',-a.margem],['Sobra estimada (mínimo zero)',a.sobra]].map(([n,v])=>`<div><span>${n}</span><b>${R(v)}</b></div>`).join('')}</div><p class="nota">A reserva já guardada fica fora do caixa. Entradas futuras e despesas não cadastradas não são consideradas. ${a.gastos<=0?'Sem histórico de gastos, a sobra não representa capacidade de aporte.':''}</p></details>
 <div class="radar-layout"><div>${perfilHTML(p)}${distribuicao(a,p,d)}</div><div><section class="panel"><div class="radar-section"><span class="radar-step">02</span><h2>O que priorizar agora</h2></div><p class="sub">Baseado no mês atual, mesmo se outra aba estiver em um mês anterior.</p><div class="radar-reserva"><span>Reserva de emergência</span><b>${a.meses===null?'Sem histórico':num(a.meses)+' / 6 meses'}</b><div class="radar-track"><i style="width:${a.meses===null?0:Math.min(100,a.meses/6*100)}%;background:var(--g1)"></i></div><small class="mut">${R(a.reserva)} guardados · renda média ${R(d.renda)} · patrimônio líquido ${R(d.patrimonio)}</small></div><div class="radar-priorities">${a.prioridades.map(x=>`<article class="radar-priority ${x.tom}"><h3>${x.titulo}</h3><p>${x.texto}</p>${x.go?`<button class="lnk" data-go="${x.go}">Ver ${esc(x.go==='geral'?'visão geral':x.go)} →</button>`:''}</article>`).join('')}</div></section>
 <section class="panel"><div class="radar-section"><span class="radar-step">04</span><h2>Caminhos para explorar</h2></div><div class="radar-education"><h3>Reserva e curto prazo</h3><p>Priorize menor volatilidade, prazo de resgate e liquidez compatível com a necessidade.</p><details><summary>Exemplos para estudar</summary><p>Tesouro Selic e CDB com liquidez diária, verificando resgate, tributação, risco do emissor e condições do produto.</p></details><h3>Objetivos de longo prazo</h3><p>Estude diversificação e proteção contra inflação conforme o perfil, sem usar o dinheiro de compromissos próximos.</p><details><summary>Exemplos para estudar</summary><p>Títulos indexados à inflação com vencimento alinhado à meta, fundos, ações e ETFs, inclusive exposição internacional. Fundos, ações e ETFs podem perder valor e não contam com FGC.</p></details></div>${simulador()}</section></div></div>
 <section class="panel">${mercadoHTML(a,p)}${metodologia()}<p class="nota">Informação educativa, sem execução de compras. Fontes: <a class="lnk" href="https://brapi.dev/docs" target="_blank" rel="noopener noreferrer">brapi</a> · <a class="lnk" href="https://www.tesourodireto.com.br/" target="_blank" rel="noopener noreferrer">Tesouro Direto</a> · <a class="lnk" href="https://www.fgc.org.br/sobre-garantia-fgc" target="_blank" rel="noopener noreferrer">FGC</a>. A cobertura informada tem limites por CPF/CNPJ e conglomerado; confirme na fonte.</p></section></div>`;}
function bind(root,ctx){const form=root.querySelector('#radarPerfil');form?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(form),r=Q.map((_,i)=>Number(f.get('rp'+i)));if(!C.perfil(r))return;prefs.respostas=r;const ok=salvar();ctx.redraw();ctx.toast(ok?'Perfil salvo neste navegador':'Perfil aplicado; não foi possível salvar neste navegador.');});
 root.querySelectorAll('[data-radar-class]').forEach(sel=>sel.addEventListener('change',()=>{prefs.classes={...(prefs.classes||{}),[sel.dataset.radarClass]:sel.value};if(!salvar())ctx.toast('Classificação aplicada; não foi possível salvar neste navegador.');ctx.redraw();}));
 root.querySelectorAll('[data-radar-tab]').forEach(b=>b.addEventListener('click',()=>{aba=b.dataset.radarTab;ctx.redraw();}));
 root.querySelector('[data-radar="atualizar"]')?.addEventListener('click',async()=>{if(carregando)return;if(Date.now()-ultimo<60000){ctx.toast('Aguarde um minuto entre consultas.');return}carregando=true;ultimo=Date.now();erro='';const owner=conta;ctx.redraw();try{const data=await Promise.race([ctx.fetchMarket(),new Promise((_,reject)=>setTimeout(()=>reject(new Error('tempo')),25000))]);if(conta!==owner)return;if(!data||!Array.isArray(data.stocks)||!Array.isArray(data.treasury)||!Array.isArray(data.offers))throw new Error('formato');mercado=data;if(data.cdi&&!C.recente(data.cdi.asOf))mercado.cdi=null;}catch{if(conta===owner)erro='Não foi possível consultar o mercado. A conexão precisa estar ativada; tente novamente mais tarde. O planejamento continua disponível.';}finally{carregando=false;if(conta===owner)ctx.redraw();}});
 const sim=root.querySelector('#radarSim');sim?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(sim),parse=s=>{s=String(s??'').trim();if(s.includes(','))s=s.replace(/\./g,'').replace(',','.');return s===''?NaN:Number(s)},r=C.simular({capital:parse(f.get('capital')),dias:parse(f.get('dias')),taxa:parse(f.get('taxa')),tipo:f.get('tipo'),cdi:parse(f.get('cdi')),isento:f.has('isento')});const el=root.querySelector('#radarSimResultado');el.innerHTML=r?`<div class="radar-cash-lines">${[['Ganho bruto',r.bruto],['IOF estimado',r.iof],['IR estimado ('+pct(r.irAliq*100)+')',r.ir],['Ganho líquido estimado',r.liquido],['Valor final estimado',r.final]].map(([n,v])=>`<div><span>${n}</span><b>${R(v)}</b></div>`).join('')}</div>`:'Preencha valores positivos, prazo inteiro de 1 a 36.500 dias e, para % do CDI, a premissa anual de CDI.';ctx.mark(el);});
}
window.ControleRadar={render,bind};
})();
